openapi: 3.1.0

info:
  title: Posibly API
  version: 0.0.1

tags:
  - name: Authentication
    description: Authentication actions
  - name: Outlet Resource
    description: Manage company or shop resources information
  - name: Employee
    description: Manage employee users
  - name: User
    description: Manage users
  - name: Transaction
    description: Manage transactions of an outlet

paths:
  /admin/users:
    $ref: "./resources/auth-sign-up-admin.yaml"
  /auth/sign-up/personal:
    $ref: "./resources/auth-sign-up-personal.yaml"
  /auth/sign-up/business:
    $ref: "./resources/auth-sign-up-business.yaml"
  /auth/sign-in:
    $ref: "./resources/auth-sign-in.yaml"
  /auth/sign-out:
    $ref: "./resources/auth-sign-out.yaml"
  /auth/refresh:
    $ref: "./resources/auth-refresh.yaml"
  /auth/info:
    $ref: "./resources/auth-info.yaml"

  /outlets:
    $ref: "./resources/outlets.yaml"
  /outlets/{outletId}:
    $ref: "./resources/outlets-id.yaml"

  /outlets/{outletId}/employees:
    $ref: "./resources/outlets-id-employees.yaml"
  /outlets/{outletId}/employees/{employeeId}:
    $ref: "./resources/outlets-id-employee-id.yaml"

  /outlets/{outletId}/categories:
    $ref: "./resources/outlets-id-categories.yaml"
  /outlets/{outletId}/categories/{categoryId}:
    $ref: "./resources/outlets-id-categories-id.yaml"

  /outlets/{outletId}/products:
    $ref: "./resources/outlets-id-products.yaml"
  /outlets/{outletId}/products/{productId}:
    $ref: "./resources/outlets-id-products-id.yaml"

  /outlets/{outletId}/taxes:
    $ref: "./resources/outlets-id-taxes.yaml"
  /outlets/{outletId}/taxes/{taxId}:
    $ref: "./resources/outlets-id-taxes-id.yaml"

  /outlets/{outletId}/discounts:
    $ref: "./resources/outlets-id-discounts.yaml"
  /outlets/{outletId}/discounts/{discountId}:
    $ref: "./resources/outlets-id-discounts-id.yaml"

  /outlets/{outletId}/orders:
    $ref: "./resources/outlets-id-orders.yaml"
  /outlets/{outletId}/orders/{orderId}:
    $ref: "./resources/outlets-id-orders-id.yaml"

  /outlets/{outletId}/stocks:
    $ref: "./resources/auth-info.yaml"
  /outlets/{outletId}/stocks/{stockId}:
    $ref: "./resources/auth-info.yaml"

components:
  parameters:
    $ref: "./params/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  securitySchemes:
    $ref: "./securities/_index.yaml"
